# Generated by Django 4.2.4 on 2023-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CombatSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('specialization', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('specialization', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('species', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=200)),
                ('chance_to_appear', models.FloatField()),
                ('tameable', models.BooleanField()),
                ('befriendable', models.BooleanField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('insight', models.IntegerField()),
                ('willpower', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('persuasion', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('abilities', models.ManyToManyField(to='loremaster_app.ability')),
                ('combat_skills', models.ManyToManyField(to='loremaster_app.combatskill')),
                ('harvested_materials', models.ManyToManyField(to='loremaster_app.material')),
                ('skills', models.ManyToManyField(to='loremaster_app.skill')),
                ('special_abilities', models.ManyToManyField(to='loremaster_app.specialability')),
                ('spells', models.ManyToManyField(to='loremaster_app.spell')),
                ('treasure', models.ManyToManyField(to='loremaster_app.treasure')),
            ],
        ),
    ]
