# Generated by Django 4.2.4 on 2023-09-17 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loremaster_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunityOrResistanceOrWeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200)),
                ('resistant_or_weak_level', models.IntegerField()),
                ('is_immune', models.BooleanField(default=False)),
                ('racial_ability', models.BooleanField(default=False)),
                ('racial_level', models.PositiveIntegerField(blank=True, null=True)),
                ('is_maneuver', models.BooleanField(default=False)),
                ('is_flaw', models.BooleanField(default=False)),
                ('is_talent', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='monster',
            name='combat_skills',
        ),
        migrations.AddField(
            model_name='ability',
            name='is_flaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='is_maneuver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='racial_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='racial_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combatskill',
            name='is_flaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatskill',
            name='is_maneuver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatskill',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatskill',
            name='racial_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combatskill',
            name='racial_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_flaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_maneuver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='racial_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='racial_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialability',
            name='is_flaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialability',
            name='is_maneuver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialability',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialability',
            name='racial_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialability',
            name='racial_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='casting_type',
            field=models.CharField(choices=[('damage', 'Damage'), ('healing', 'Healing'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='category',
            field=models.CharField(choices=[('offensive_arcane', 'Offensive Arcane (Component Based)'), ('buff', 'Buff'), ('debuff', 'Debuff')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.TextField(help_text='List of components required for the spell.', null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='cost',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='ease_of_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_flaw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_maneuver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='materials',
            field=models.ManyToManyField(blank=True, to='loremaster_app.material'),
        ),
        migrations.AddField(
            model_name='spell',
            name='racial_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='racial_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='school_of_magic',
            field=models.CharField(blank=True, choices=[('arcane', 'Arcane')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='combatskill',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='combatskill',
            name='specialization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monster',
            name='befriendable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monster',
            name='chance_to_appear',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='tameable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='specialization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specialability',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='monster',
            name='immunities_or_resistances',
            field=models.ManyToManyField(to='loremaster_app.immunityorresistanceorweak'),
        ),
    ]
